theme: jekyll-theme-architect
# Моя подія:
<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=NmRiYmp0NDFiMWtxOGxrZ3JwbWw4c3M4cWsgbHV0Y2hpbjIwMDFAbQ&amp;tmsrc=lutchin2001%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_uk.gif"></a>
